export const ACTIONRSCF = {
  SET_LOGIN_STATUS: "SET_LOGIN_STATUS",
  RESET: "RESET",
  SET_CLIENT_DETAILS: "SET_CLIENT_DETAILS",
  GET_ALL_GOODS: "GET_ALL_GOODS",
  GET_SOME_GOODS: "GET_SOME_GOODS",
  SET_NEW_GOOD: "SET_NEW_GOOD",
  GET_CLIENTLIST: "GET_CLIENTLIST",
  SET_SEARCHED_GOOD: "SET_SEARCHED_GOOD",
  SET_NEW_ORDER: "SET_NEW_ORDER",
  GET_GOOD_ORDERS: "GET_GOOD_ORDERS",
};
